# Generated by Django 3.0.12 on 2021-03-05 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('creation_date', models.DateField(blank=True, verbose_name='Fecha creacion')),
                ('modified', models.DateField(blank=True, verbose_name='Fecha modificacion')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation', models.CharField(blank=True, max_length=999, null=True)),
                ('compraRepresentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representa', to='compras.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='DetCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.CharField(max_length=160, verbose_name='Kilos')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('bonus', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Fecha creacion')),
                ('modified', models.DateField(blank=True, null=True, verbose_name='Fecha modificacion')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compratodet', to='compras.Compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material')),
            ],
        ),
    ]
