# Generated by Django 3.0.12 on 2021-02-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nombre cliente')),
                ('material', models.CharField(max_length=150, verbose_name='Nombre material')),
                ('kilos', models.FloatField(verbose_name='Kilos')),
                ('unit_value', models.FloatField(verbose_name='Valor unitario')),
                ('total_value', models.FloatField(verbose_name='Total')),
                ('creation_date', models.DateField(verbose_name='Fecha creacion')),
                ('modified', models.DateField(verbose_name='Fecha modificacion')),
            ],
        ),
    ]
