# Generated by Django 3.0.12 on 2021-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha creacion'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='modified',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha modificacion'),
        ),
    ]
