# Generated by Django 3.0.12 on 2021-03-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210309_1622'),
        ('compras', '0002_auto_20210306_1855'),
    ]

    operations = [
    ]
