# Generated by Django 3.0.12 on 2021-02-26 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_client_active'),
        ('compras', '0002_auto_20210226_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='client_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clientes.Client'),
        ),
    ]
