# Generated by Django 3.0.12 on 2021-02-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210226_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='bonus',
            field=models.CharField(choices=[('No_aplica', 'No aplica'), ('Carton', 'Carton'), ('Archivo', 'Archivo'), ('Periodico', 'Periodico'), ('Plega', 'Plega'), ('Plastico', 'Plastico'), ('Chatarra', 'Chatarra'), ('Vidrio', 'Vidrio'), ('Otros', 'Otros')], default='No_aplica', max_length=100),
        ),
    ]
