# Generated by Django 3.0.12 on 2021-09-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210814_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detcompra',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
