# Generated by Django 3.0.12 on 2021-09-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210906_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total_value',
            field=models.IntegerField(default=0),
        ),
    ]
