# Generated by Django 3.0.12 on 2021-02-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_compra_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='kilos',
            field=models.CharField(max_length=160, verbose_name='Kilos'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total_value',
            field=models.CharField(max_length=160, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='unit_value',
            field=models.CharField(max_length=160, verbose_name='Valor unitario'),
        ),
    ]
