# Generated by Django 3.0.12 on 2021-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_auto_20210302_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detcompra',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
