# Generated by Django 3.0.12 on 2021-03-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
        ('compras', '0008_auto_20210302_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detcompra',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material'),
        ),
    ]
