# Generated by Django 3.0.12 on 2021-03-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_compra_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='modified',
        ),
    ]
