# Generated by Django 3.0.12 on 2021-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_compra_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detcompra',
            name='active',
        ),
        migrations.AlterField(
            model_name='detcompra',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
