# Generated by Django 3.0.12 on 2021-03-04 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_auto_20210303_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detcompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compratodet', to='compras.Compra'),
        ),
    ]
