# Generated by Django 3.0.12 on 2021-03-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_auto_20210304_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='detcompra',
            name='representation',
            field=models.CharField(default='a', max_length=999),
            preserve_default=False,
        ),
    ]
