# Generated by Django 3.0.12 on 2021-03-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_detcompra_representation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detcompra',
            name='representation',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
