# Generated by Django 3.0.12 on 2021-03-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_auto_20210304_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detcompra',
            name='representation',
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation', models.CharField(blank=True, max_length=999, null=True)),
                ('compra_representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Compra')),
            ],
        ),
    ]
