# Generated by Django 3.0.12 on 2021-03-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_auto_20210304_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representation',
            old_name='compra_representation',
            new_name='compraRepresentation',
        ),
    ]
