# Generated by Django 3.0.12 on 2021-03-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_auto_20210304_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='detcompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
