# Generated by Django 3.0.12 on 2021-03-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('identification', models.IntegerField(verbose_name='Cedula')),
                ('phone', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
