# Generated by Django 3.0.12 on 2021-07-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification',
            field=models.CharField(max_length=90, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=90, verbose_name='Telefono'),
        ),
    ]
