# Generated by Django 3.0.12 on 2021-03-05 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=250, verbose_name='Empresa a la que vende')),
                ('purchase', models.CharField(max_length=200, verbose_name='Empresa a la que compra')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation', models.CharField(blank=True, max_length=999, null=True)),
                ('ventaRepresentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representa', to='ventas.Ventas')),
            ],
        ),
        migrations.CreateModel(
            name='DetVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.CharField(max_length=200, verbose_name='Kilos')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_venta', to='ventas.Ventas')),
            ],
        ),
    ]
