# Generated by Django 3.0.12 on 2021-02-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=250, verbose_name='Empresa a la que vende')),
                ('material', models.CharField(max_length=250, verbose_name='Material')),
                ('kilos', models.CharField(max_length=200, verbose_name='Kilos')),
                ('unit_value', models.CharField(max_length=200, verbose_name='Valor unitario')),
                ('purchase', models.CharField(max_length=200, verbose_name='Empresa a la que compra')),
                ('create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
