# Generated by Django 3.0.12 on 2021-03-01 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20210228_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='create',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 16, 20, 7, 920528, tzinfo=utc)),
        ),
    ]
