# Generated by Django 3.0.12 on 2021-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20210301_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='create',
            field=models.DateField(blank=True),
        ),
    ]
