# Generated by Django 3.0.12 on 2021-03-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20210304_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='modified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='create',
            field=models.DateField(blank=True, null=True),
        ),
    ]
