# Generated by Django 3.0.12 on 2021-03-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_auto_20210304_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_venta', to='ventas.Ventas'),
        ),
    ]
